version: “3.7”
services:
  # main:
  #   container_name: main
  #   build:
  #     context: .
  #     target: development
  #   volumes: 
  #     - .:/usr/src/app 
  #     - /usr/src/app/node_modules
  #   ports: 
  #     - 3000:3000
  #   command: yarn start:dev
  #   env_file: — .env
  #   networks: 
  #     - api
  #   depends_on: 
  #     - postgres
  postgres:
    container_name: postgres
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=313326339
    # env_file: — .env
    ports: 
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
# networks:
#   api:
volumes:
  pgdata:
