version: "3"

services:
  app:
    container_name: payment-service
    image: payment-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3004:3004"
    env_file:
      - .env